function Hd = Discrete_Time_Filter
% Discrete_Time_Filter Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 24-Nov-2018 18:04:02

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 32;  % Sampling Frequency

Fstop1 = 1;               % First Stopband Frequency
Fpass1 = 1.5;             % First Passband Frequency
Fpass2 = 3.5;             % Second Passband Frequency
Fstop2 = 4;               % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.001;           % Second Stopband Attenuation
flag   = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 ...
                             1 0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

% [EOF]
